// import AbsMan from "../AbsMan"

/**
 * This is a JavaScript code snippet that exports an object. The object consists of two properties: types and options.
 * The types property is itself an object, which contains several nested objects. Each nested object represents a different mode that can be assigned to a variable in the system. The available types are:
 ** singleValue: A single value such as a string, number, boolean or date. Also includes a unique identifier, "id".
 ** link: Links or relationships between data entities. Includes information such as the mode of link ("Mems", "Head", "Coll", "Cons", "pair"), table name, key, and through table.
 ** aggregate: Aggregate functions such as count, sum, min, and max. Includes information such as the table name and field name for aggregation.
 ** mirror: Data mirroring options including getter and setter functions.
 ** option: Options with a single value.
 *
 * The options property is also an object containing various options that can be set on a variable, such as default value, required, uniqueness, selectability, and primary key.
 *
 * This code can be used to define the available data types and options for variables in the system this code is written for.
 */

// let inst: any = new AbsMan();

// inst.setMeta({ id: "Dimensions", title: "Dimensions", description: "Dimensions", version: "0.3" });

// let defaultParams: any = {
//     "config": {
//         "reset": true,
//         "id": "",
//         "view": true,
//         "icon": true,
//         "widget": "",
//         "defVal": "",
//         "array": [],
//         "language": [],
//         "validation": [],
//         "validtime": [],
//         "format": [],

//         "changeScale": true,

//         "unit": [],
//         "subunit": [],
//         "scaleOp": [],
//         "editable": true,
//         "furmula": [],
//     },
//     "edit": {
//         "value": "",
//         "reset": true,
//         "picker": "",
//     },
// };

// let classes: any = {
//     "single": {
//         dims: ["metaId", "integer", "float", "string"],
//         params: () => defaultParams
//     },
//     "combinations": {
//         dims: ["vector", "timeSpot", "timeDuration", "currency", "phoneNumber", "url", "address", "geo", "color", "theme"],
//         params: () => defaultParams
//     },
//     "timeStamp": {
//         dims: ["timeStamp"],
//         params: () => {
//             let params = structuredClone(defaultParams);
//             delete params.config.language;
//             params.config["event"] = [];
//             return params;
//         }
//     },
//     "link": {
//         dims: ["headMem", "collectionConsume", "pair"],
//         params: () => {
//             let params = structuredClone(defaultParams);
//             delete params.config.language;
//             delete params.config.unit;
//             delete params.config.subunit;
//             params.config["packetId"] = "";
//             return params;
//         }
//     },
//     "mirror": {
//         dims: ["count", "sum", "min", "max", "avrg", "statement"],
//         params: () => {
//             let params = structuredClone(defaultParams);
//             delete params.config.language;
//             delete params.config.unit;
//             delete params.config.subunit;
//             params.config["targetInst"] = "";
//             params.config["targetPacket"] = "";
//             return params;
//         }
//     },
//     "option": {
//         dims: ["status", "freeStyle", "boolean", "prority", "iconSet", "wizard"],
//         params: () => {
//             let params = structuredClone(defaultParams);
//             delete params.config.unit;
//             delete params.config.subunit;
//             params.config["optionList"] = [];
//             params.config["grDependancy"] = "";
//             return params;
//         }
//     },
//     "arrayGrouping": {
//         dims: ["arrayGrouping"],
//         params: () => defaultParams
//     },
//     "dictionary": {
//         dims: ["dictionary"],
//         params: () => defaultParams
//     },
//     "content": {
//         dims: ["audio", "image", "video"],
//         params: () => defaultParams
//     },
//     "password": {
//         dims: ["passbolt"],
//         params: () => {
//             let params = structuredClone(defaultParams);
//             delete params.config.language;
//             return params;
//         }
//     },
//     "method": {
//         dims: ["script", "library", "play"],
//         params: () => {
//             let params = structuredClone(defaultParams);
//             delete params.config.language;
//             return params;
//         }
//     },
//     "dpendentNtt": {
//         dims: ["reg", "config", "plug", "class", "ntt", "index"],
//         params: () => {
//             let params = structuredClone(defaultParams);
//             delete params.config.language;
//             return params;
//         }
//     },
//     "root": {
//         dims: ["treeMode"],
//         params: () => {
//             let params = structuredClone(defaultParams);
//             delete params.config.language;
//             return params;
//         }
//     },
//     "assign": {
//         dims: ["assign"],
//         params: () => defaultParams
//     },
//     "seperator": {
//         dims: ["seperator"],
//         params: () => defaultParams
//     },
//     "collection": {
//         dims: ["collection"],
//         params: () => defaultParams
//     },
// };

// for (const packetId of Object.keys(classes)) {
//     inst.addPack(packetId, "body");
//     inst.setPack(packetId, { "title": `${packetId} Value`, "description": `${packetId} Dimension class` });

//     for (const fieldId of classes[packetId].dims) {
//         inst.addField(packetId, fieldId);
//         inst.setField(packetId, fieldId, { "title": fieldId, "description": `${fieldId} dimension` });
//         inst.registerDimension(packetId, fieldId, classes[packetId].params());
//     }
// }

// console.log('====================================');
// console.log(inst.NTT, "salammm");
// console.log('====================================');

const Dimensions: any = {
  meta: {
    id: "Dimensions",
    title: "Dimensions",
    version: "0.3",
    lastUpdate: "",
    owner: "",
    type: "",
    description: "Dimensions",
    absManVersion: "0.1",
  },
  single: {
    meta: {
      axis: "body",
      title: "single Value",
      description: "single Dimension class",
    },
    metaId: {
      meta: {
        title: "metaId",
        dim: "metaId",
        description: "metaId dimension",
        dimClass: "single",
      },
      order: 0,
      config: {
        id: "",
        widget: "input",
        defVal: "",
        reset: true,
        view: true,
        icon: true,
        changeScale: true,
        editable: true,
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        unit: [],
        subunit: [],
        scaleOp: [],
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    integer: {
      meta: {
        title: "integer",
        dim: "integer",
        description: "integer dimension",
        dimClass: "single",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "input:number",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    float: {
      meta: {
        title: "float",
        dim: "float",
        description: "float dimension",
        dimClass: "single",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "input",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    string: {
      meta: {
        title: "string",
        dim: "string",
        description: "string dimension",
        dimClass: "single",
      },
      order: 0,
      config: {
        id: "",
        widget: "input:text",
        defVal: "",
        reset: true,
        view: true,
        icon: true,
        changeScale: true,
        editable: true,
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        unit: [],
        subunit: [],
        scaleOp: [],
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  combinations: {
    meta: {
      axis: "body",
      title: "combinations Value",
      description: "combinations Dimension class",
    },
    vector: {
      meta: {
        title: "vector",
        dim: "vector",
        description: "vector dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    timeSpot: {
      meta: {
        title: "timeSpot",
        dim: "timeSpot",
        description: "timeSpot dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    timeDuration: {
      meta: {
        title: "timeDuration",
        dim: "timeDuration",
        description: "timeDuration dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    currency: {
      meta: {
        title: "currency",
        dim: "currency",
        description: "currency dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    phoneNumber: {
      meta: {
        title: "phoneNumber",
        dim: "phoneNumber",
        description: "phoneNumber dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    url: {
      meta: {
        title: "url",
        dim: "url",
        description: "url dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "url",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    upload: {
      meta: {
        title: "upload",
        dim: "upload",
        description: "upload dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "upload",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    code: {
      meta: {
        title: "code",
        dim: "code",
        description: "code dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "editor",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    address: {
      meta: {
        title: "address",
        dim: "address",
        description: "address dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    geo: {
      meta: {
        title: "geo",
        dim: "geo",
        description: "geo dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    color: {
      meta: {
        title: "color",
        dim: "color",
        description: "color dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "colorPicker",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    theme: {
      meta: {
        title: "theme",
        dim: "theme",
        description: "theme dimension",
        dimClass: "combinations",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  timeStamp: {
    meta: {
      axis: "body",
      title: "timeStamp Value",
      description: "timeStamp Dimension class",
    },
    timeStamp: {
      meta: {
        title: "timeStamp",
        dim: "timeStamp",
        description: "timeStamp dimension",
        dimClass: "timeStamp",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
        event: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  link: {
    meta: {
      axis: "body",
      title: "link Value",
      description: "link Dimension class",
    },
    headMem: {
      meta: {
        title: "headMem",
        dim: "headMem",
        description: "headMem dimension",
        dimClass: "link",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        packetId: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    collectionConsume: {
      meta: {
        title: "collectionConsume",
        dim: "collectionConsume",
        description: "collectionConsume dimension",
        dimClass: "link",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        packetId: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    pair: {
      meta: {
        title: "pair",
        dim: "pair",
        description: "pair dimension",
        dimClass: "link",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        packetId: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  mirror: {
    meta: {
      axis: "body",
      title: "mirror Value",
      description: "mirror Dimension class",
    },
    count: {
      meta: {
        title: "count",
        dim: "count",
        description: "count dimension",
        dimClass: "mirror",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        targetInst: "",
        targetPacket: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    sum: {
      meta: {
        title: "sum",
        dim: "sum",
        description: "sum dimension",
        dimClass: "mirror",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        targetInst: "",
        targetPacket: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    min: {
      meta: {
        title: "min",
        dim: "min",
        description: "min dimension",
        dimClass: "mirror",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        targetInst: "",
        targetPacket: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    max: {
      meta: {
        title: "max",
        dim: "max",
        description: "max dimension",
        dimClass: "mirror",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        targetInst: "",
        targetPacket: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    avrg: {
      meta: {
        title: "avrg",
        dim: "avrg",
        description: "avrg dimension",
        dimClass: "mirror",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        targetInst: "",
        targetPacket: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    statement: {
      meta: {
        title: "statement",
        dim: "statement",
        description: "statement dimension",
        dimClass: "mirror",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        targetInst: "",
        targetPacket: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  option: {
    meta: {
      axis: "body",
      title: "option Value",
      description: "option Dimension class",
    },
    status: {
      meta: {
        title: "status",
        dim: "status",
        description: "status dimension",
        dimClass: "option",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "dropdown",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        optionList: [],
        grDependancy: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    freeStyle: {
      meta: {
        title: "freeStyle",
        dim: "freeStyle",
        description: "freeStyle dimension",
        dimClass: "option",
      },
      order: 0,
      config: {
        id: "",
        widget: "dropdown",
        defVal: "",
        grDependancy: "",
        reset: true,
        view: true,
        icon: true,
        changeScale: true,
        editable: true,
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        scaleOp: [],
        furmula: [],
        optionList: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    boolean: {
      meta: {
        title: "boolean",
        dim: "boolean",
        description: "boolean dimension",
        dimClass: "option",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "dropdown:boolean",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        optionList: [],
        grDependancy: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    prority: {
      meta: {
        title: "prority",
        dim: "prority",
        description: "prority dimension",
        dimClass: "option",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "dropdown",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        optionList: [],
        grDependancy: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    iconSet: {
      meta: {
        title: "iconSet",
        dim: "iconSet",
        description: "iconSet dimension",
        dimClass: "option",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "dropdown",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        optionList: [],
        grDependancy: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    wizard: {
      meta: {
        title: "wizard",
        dim: "wizard",
        description: "wizard dimension",
        dimClass: "option",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "dropdown",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        scaleOp: [],
        editable: true,
        furmula: [],
        optionList: [],
        grDependancy: "",
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  arrayGrouping: {
    meta: {
      axis: "body",
      title: "arrayGrouping Value",
      description: "arrayGrouping Dimension class",
    },
    arrayGrouping: {
      meta: {
        title: "arrayGrouping",
        dim: "arrayGrouping",
        description: "arrayGrouping dimension",
        dimClass: "arrayGrouping",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "code:json",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  dictionary: {
    meta: {
      axis: "body",
      title: "dictionary Value",
      description: "dictionary Dimension class",
    },
    dictionary: {
      meta: {
        title: "dictionary",
        dim: "dictionary",
        description: "dictionary dimension",
        dimClass: "dictionary",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "code:json",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  content: {
    meta: {
      axis: "body",
      title: "content Value",
      description: "content Dimension class",
    },
    audio: {
      meta: {
        title: "audio",
        dim: "audio",
        description: "audio dimension",
        dimClass: "content",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    image: {
      meta: {
        title: "image",
        dim: "image",
        description: "image dimension",
        dimClass: "content",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    video: {
      meta: {
        title: "video",
        dim: "video",
        description: "video dimension",
        dimClass: "content",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  password: {
    meta: {
      axis: "body",
      title: "password Value",
      description: "password Dimension class",
    },
    passbolt: {
      meta: {
        title: "passbolt",
        dim: "passbolt",
        description: "passbolt dimension",
        dimClass: "password",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  method: {
    meta: {
      axis: "body",
      title: "method Value",
      description: "method Dimension class",
    },
    script: {
      meta: {
        title: "script",
        dim: "script",
        description: "script dimension",
        dimClass: "method",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    library: {
      meta: {
        title: "library",
        dim: "library",
        description: "library dimension",
        dimClass: "method",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    play: {
      meta: {
        title: "play",
        dim: "play",
        description: "play dimension",
        dimClass: "method",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  dpendentNtt: {
    meta: {
      axis: "body",
      title: "dpendentNtt Value",
      description: "dpendentNtt Dimension class",
    },
    reg: {
      meta: {
        title: "reg",
        dim: "reg",
        description: "reg dimension",
        dimClass: "dpendentNtt",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    config: {
      meta: {
        title: "config",
        dim: "config",
        description: "config dimension",
        dimClass: "dpendentNtt",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    plug: {
      meta: {
        title: "plug",
        dim: "plug",
        description: "plug dimension",
        dimClass: "dpendentNtt",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    class: {
      meta: {
        title: "class",
        dim: "class",
        description: "class dimension",
        dimClass: "dpendentNtt",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    ntt: {
      meta: {
        title: "ntt",
        dim: "ntt",
        description: "ntt dimension",
        dimClass: "dpendentNtt",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
    index: {
      meta: {
        title: "index",
        dim: "index",
        description: "index dimension",
        dimClass: "dpendentNtt",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  root: {
    meta: {
      axis: "body",
      title: "root Value",
      description: "root Dimension class",
    },
    treeMode: {
      meta: {
        title: "treeMode",
        dim: "treeMode",
        description: "treeMode dimension",
        dimClass: "root",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  assign: {
    meta: {
      axis: "body",
      title: "assign Value",
      description: "assign Dimension class",
    },
    assign: {
      meta: {
        title: "assign",
        dim: "assign",
        description: "assign dimension",
        dimClass: "assign",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  seperator: {
    meta: {
      axis: "body",
      title: "seperator Value",
      description: "seperator Dimension class",
    },
    seperator: {
      meta: {
        title: "seperator",
        dim: "seperator",
        description: "seperator dimension",
        dimClass: "seperator",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
  collection: {
    meta: {
      axis: "body",
      title: "collection Value",
      description: "collection Dimension class",
    },
    collection: {
      meta: {
        title: "collection",
        dim: "collection",
        description: "collection dimension",
        dimClass: "collection",
      },
      order: 0,
      config: {
        reset: true,
        id: "",
        view: true,
        icon: true,
        widget: "",
        defVal: "",
        array: [],
        language: [],
        validation: [],
        validtime: [],
        format: [],
        changeScale: true,
        unit: [],
        subunit: [],
        scaleOp: [],
        editable: true,
        furmula: [],
      },
      edit: {
        value: "",
        reset: true,
        picker: "",
      },
    },
  },
};

export default Dimensions;
